# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[52,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="${mod_license}"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# If your mod is purely client-side and has no multiplayer functionality (be it dedicated servers or Open to LAN),
# set this to true, and Forge will set the correct displayTest for you and skip loading your mod on dedicated servers.
#clientSideOnly=true #optional - defaults to false if absent
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="${mod_id}" #mandatory
# The version number of the mod
version="1.21.4-Forge_54.1.0_V2.0 | PinkCabbage Transparent BetterScreen" #mandatory
# A display name for the mod
displayName="粉红大包菜的屏幕透明度优化" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="Logo.png" #optional
# A text field displayed in the mod UI
#credits="" #optional
# A text field displayed in the mod UI
authors="粉红大包菜（PinkCabbage）" #optional
# Display Test controls the display for your mod in the server connection screen
# MATCH_VERSION means that your mod will cause a red X if the versions on client and server differ. This is the default behaviour and should be what you choose if you have server and client elements to your mod.
# IGNORE_SERVER_VERSION means that your mod will not cause a red X if it's present on the server but not on the client. This is what you should use if you're a server only mod.
# IGNORE_ALL_VERSION means that your mod will not cause a red X if it's present on the client or the server. This is a special case and should only be used if your mod has no server component.
# NONE means that no display test is set on your mod. You need to do this yourself, see IExtensionPoint.DisplayTest for more information. You can define any scheme you wish with this value.
# IMPORTANT NOTE: this is NOT an instruction as to which environments (CLIENT or DEDICATED SERVER) your mod loads on. Your mod should load (and maybe do nothing!) whereever it finds itself.
#displayTest="MATCH_VERSION" # if nothing is specified, MATCH_VERSION is the default when clientSideOnly=false, otherwise IGNORE_ALL_VERSION when clientSideOnly=true (#optional)

# The description text for the mod (multi line!) (#mandatory)
description='''粉红大包菜（PinkCabbage），又名粉红大包，是轩天工作室负责人
QQ_Email:1980453573@qq.com，
轩天工作室交流QQ群:774718671，
作者的模组交流QQ群:671389632，
本模组的代码是开源的并且我还写了很多注释比较适合模组学习者:
https://github.com/BigPinkCabbage/1.21.4-Forge_54.1.0_V2.0-PinkCabbage-Transparent-BetterScreen
但是本模组用的是CC BY-NC 4.0协议，禁止修改者商业化使用，
你可以转载我的作品到短视频平台分享，但是要标注出处，
以下是CC BY-NC 4.0协议的基本要求↓↓↓
https://creativecommons.org/licenses/by-nc/4.0/

模组功能:
1.玩家在水中移动时会有泡泡粒子特效，(不太完善的功能所以被作者删去了，可以在源码的UnderwaterBubblesHandler类找到)
2.玩家手持物品切换到工具时该工具的耐久度会在原版游戏的工具名称悬浮文本下方显示，玩家手持工具点击左键时可以再次显示耐久度(无需攻击到实体也能显示)
3.玩家的坐标和服务器延迟时间(ms)的数据分别在屏幕左上角和右下角显示，玩家的装备耐久度和背包里面弓箭的数量以及手持食物的饥饿度会在快捷栏显示
4.模组还可以通过设置菜单里面的滑轮来调节玩家物品栏和快捷栏以及一些容器方块的UI背景的透明度(打开菜单的默认按键为J)
5.是否显示以上功能都可以在菜单修改，更改模组默认按键的路径为:游戏选项->按键控制->按键绑定->最后找到“粉红大包菜的按键”
6./CabbageMod help 这个命令会有模组按键和命令相关的文字提示
7.模组添加的透明度参数也支持玩家在聊天栏使用命令修改，例如/CabbageMod InventoryAlpha 1.0 (这里的参数可以写0.0到1.0范围中的小数，但是SettingScreenAlpha的范围是0.1 ~ 1.0)
8.模组菜单内的一些参数还可以通过版本文件夹内config文件夹里面的"PinkCabbage_settings.json"进行修改，但是请不要改错，因为这样可能会让游戏出现异常
9.模组后续还会继续优化和更新，内容如有更新也会发布在哔哩哔哩等短视频平台，搜粉红大包菜即可


PinkCabbage, also known as Pink Bag, is developed by XuanTian Studio, led by its creator.
Contact (QQ/Email): 1980453573@qq.com
XuanTian Studio QQ Group: 774718671
Mod Discussion QQ Group: 671389632
This mod is open-source and includes many comments in the code, making it suitable for learners interested in Minecraft mod development:
https://github.com/BigPinkCabbage/1.21.4-Forge_54.1.0_V2.0-PinkCabbage-Transparent-BetterScreen
However, it is licensed under CC BY-NC 4.0, which prohibits any commercial use or monetization of modified versions.
You are free to share or repost this work on short video platforms, but please include proper credit.
License info: https://creativecommons.org/licenses/by-nc/4.0/

Mod Features:
1. Bubble Particles in Water: players emit bubbles while moving underwater (feature removed; see UnderwaterBubblesHandler class).
2. Durability Display: tool durability is shown below item names and also triggered on left-click, even without hitting anything.
3. On-Screen Info: coordinates and server ping are shown on screen corners; durability, arrow count, and food value are shown on hotbar.
4. Adjustable UI Transparency: inventory and container UI backgrounds can be made transparent via settings (default key: J).
5. Configurable UI: toggle features in the settings menu. Keybinding path: Options -> Controls -> Key Bindings -> “PinkCabbage Keys”.
6. Help Command: type /CabbageMod help for in-game mod tips and key info.
7. Chat Commands: set transparency using /CabbageMod InventoryAlpha 1.0 (range: 0.0 ~ 1.0, but SettingScreenAlpha: 0.1 ~ 1.0).
8. Config File: settings also saved in config/PinkCabbage_settings.json. Be careful editing it manually.
9. Ongoing Updates: future versions will be posted to platforms like Bilibili — search for 粉红大包菜.
'''


# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.${mod_id}]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[52,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the dependency is not mandatory
    # BEFORE - This mod is loaded BEFORE the dependency
    # AFTER - This mod is loaded AFTER the dependency
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT, or SERVER
    side="BOTH"
# Here's another dependency

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
modId="cabbagejellypack"
mandatory=true
versionRange="[${mod_version},)"
ordering="NONE"
side="CLIENT"
# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
